;//////////////////////////////////////////////////////////////////////////////
;FILE: Water.ini (System)
;//////////////////////////////////////////////////////////////////////////////

WaterSet MORNING
  SkyTexture = TSCloudWis.tga
  WaterTexture = TSWater.tga
  Vertex00Color = R:200 G:200 B:200
  Vertex10Color = R:200 G:200 B:200
  Vertex01Color = R:200 G:200 B:200
  Vertex11Color = R:200 G:200 B:200
  DiffuseColor   = R:175 G:175 B:175 A:255
  TransparentDiffuseColor = R:150 G:150 B:150 A:128
  UScrollPerMS = 0.0015
  VScrollPerMS = 0.0010
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 24
End

WaterSet AFTERNOON
  SkyTexture = TSCloudWis.tga
  WaterTexture = TSWater.tga
  Vertex00Color = R:225 G:225 B:225
  Vertex10Color = R:225 G:225 B:225
  Vertex01Color = R:225 G:225 B:225
  Vertex11Color = R:225 G:225 B:225
  DiffuseColor   = R:185 G:185 B:185 A:255
  TransparentDiffuseColor = R:220 G:230 B:235 A:128
  UScrollPerMS = 0.0015
  VScrollPerMS = 0.0010
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 24
End

WaterSet EVENING
  SkyTexture = TSCloudSun.tga
  WaterTexture = TSWater.tga
  Vertex00Color = R:150 G:150 B:150
  Vertex10Color = R:150 G:150 B:150
  Vertex01Color = R:150 G:150 B:150
  Vertex11Color = R:150 G:150 B:150
  DiffuseColor   = R:225 G:225 B:225 A:255
  TransparentDiffuseColor = R:150 G:150 B:150 A:96
  UScrollPerMS = 0.0012
  VScrollPerMS = 0.0008
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 24
End

WaterSet NIGHT
  SkyTexture = TSStarFeld.tga
  WaterTexture = TSWater.tga
  Vertex00Color = R:255 G:255 B:255 A:255
  Vertex10Color = R:255 G:255 B:255 A:255
  Vertex01Color = R:255 G:255 B:255 A:255
  Vertex11Color = R:255 G:255 B:255 A:255
  DiffuseColor   = R:100 G:100 B:100 A:255
  TransparentDiffuseColor = R:180 G:190 B:210 A:112
  UScrollPerMS = 0.0006
  VScrollPerMS = 0.0004
  SkyTexelsPerUnit = 1.6
  WaterRepeatCount = 24
End

WaterTransparency
  TransparentWaterDepth = 10.0
  TransparentWaterMinOpacity = 0.77
  RiverTransparencyMultiplier = 0.95
  StandingWaterColor = R:255 G:255 B:255
  StandingWaterTexture = TWWater01.tga
  AdditiveBlending = no
  RadarWaterColor = R:140 G:140 B:255
  ReflectionGuard = X:0.0 Y:0.0
End
